# this file is *not* meant to cover or endorse the use of GitHub Actions, but rather to
# help test this project

name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: [3]
        platform: [windows-latest]
        py2exe: ['legacy', 'freeze']
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install build dependencies
      run: python -m pip install -U setuptools versioneer wheel
    - name: Install py2exe from PyPI
      run: python -m pip install py2exe
      if: matrix.py2exe == 'legacy'
    - name: Install py2exe from GitHub artifacts
      run: |
        python -m pip install tools/py2exe-0.12.0.0-cp310-cp310-win_amd64.whl
      if: matrix.py2exe == 'freeze'
    - run: python setup.py py2exe
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
    - run: dist/sample.exe
